### ISSUE TITLE
Nome do jogo

### ISSUE THREAD

**Issue by VelocityIsntSpeed** [VelocityIsNotSpeed/Grupo42-IntProg1#12]
O nome atual e provisório é "Jogo42". Temos que definir um nome definitivo e melhor.

Quando definirmos, seria bom renomear o repositório (nome atual: "Grupo42-IntProg1") também. Assim como a pasta contendo o projeto CB, e nome do projeto CB.

**Comment by Marcos-Fidelis** [comment]
"A Historia de Assis"
sim eu to 100% indo pro trocadilho de machado de assis

**Comment by VelocityIsntSpeed** [comment]
@Marcos-Fidelis Pra não ficar tão na cara, acho melhor algo tipo:
- Hassís

- Assíz

**Comment by VelocityIsntSpeed** [comment]
As Aventuras de Assis
